### ISSUE TITLE
Informações sobre o pull request

### ISSUE THREAD

**Issue by nmaia-zz** [hurbcom/challenge-bravo#12]
Pessoal, bom dia.

A respeito do bug relatado na documentação do pull request "README_API_PROJECT.md" sobre o swagger (inclusão da barra após o último parâmetro, caso seja numérico) estou trabalhando em melhorias para que a correção não fique apenas no front mas também no back-end. Com isso também será possível testar a requisição sem a inclusão da barra via swagger (como descrito no realme do peojeto).

Outro ponto importante, após inclusão do regex no front, os formatos aceitos para amount são: 100 - 1000.00 - 1000,00 - 100000.00 - 100000,00. Resumindo, utilizei apenas separadores de decimais (dois dígitos) e não de milhar. Não há validação para números negativos se não me engano, portanto caso testem esse input é possível que retorne erro.

Propostas para melhoria:
- Definição de uma cultura padrão para forçar o tratamento dos decimais d acordo com a cultura;
- Conversão do parâmetro amount de decimal para string;

Sobre o docker, ainda estou lendo a documentação para entender como funciona a ferramenta. Mas caso queiram testar a interface, posso publicar o projeto e passar a url postar aqui.  :)

Abraço

**Comment by nmaia-zz** [comment]
typo:

realme -> readme*

**Comment by nmaia-zz** [comment]
Como melhoria também seria uma sugestão, utilizar máscara de moeda no front. ;)

**Comment by nmaia-zz** [comment]
Sobre os formatos do parâmetro amount no front, reparem os separadores de decimal podem ser ponto (.) ou vírgula(,).

**Comment by zanaca** [comment]
Coloca esses pontos no próprio código, por favor!

**Comment by nmaia-zz** [comment]
Ok @zanaca , vou colocar essas observações no readme do desafio.

**Comment by nmaia-zz** [comment]
Informações adicionadas no readme:

[README_API_PROJECT.md](https://github.com/nmaia/challenge-bravo/blob/develop/README_API_PROJECT.md)
