### ISSUE TITLE
Teste de estresse

### ISSUE THREAD

**Issue by Andre335** [hurbcom/challenge-bravo#124]
Boa noite pessoal, vi que um dos requisitos do desafio é a API suportar 1000 requests por segundo num teste de estresse. 

Como as APIs externas de conversão cambial que achei tem um limite de requisições por mês de cerca de 1000 requests, vou precisar fazer com que a minha API faça muito poucas consultas a uma API externa permitindo a conversão entre as moedas suportadas. Dai, tenho algumas perguntas:

1) Qual a quantidade máxima de moedas que podem ser suportadas? Seria o total no mundo todo (cerca de 180)?
2) Tendo em vista que trabalhando com conversão entre todas as 180 moedas, teríamos cerca de 32k possíveis conversões, é aceitável um erro de precisão na conversão (poder chegar até 0.1%)? Isso seria para reduzir o número de consultas a API externa (fazendo a conversão da moeda FROM para USD e de USD para TO)
3) Tem alguma API de conversão de moedas que vocês recomendariam usar?

**Comment by brunofurmon** [comment]
Boa noite!

1 - Não há uma quantidade máxima de moedas suportadas, mas há o mínimo das 5 listadas . Todas adicionadas deverão permitir conversões válidas (reais). 
2 - Não há um limite máximo de erro percentual para conversão. Em todo caso, se houver perda de precisão por algum processo, uma justificativa cai bem :)
3 - Não há nenhuma preferência dentre os serviços externos. O importante é alcançar as métricas descritas no desafio.
Abs.,
