### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by nmaia-zz** [hurbcom/challenge-bravo#13]
Pessoal, bom dia.

Apenas informando, desde o início do desenvolvimento do projeto tive a preocupação de não gerar boilerplates no código do projeto, portanto, os únicos pontos onde é possível verificar boilerplates é nos arquivos de configuração. ex: web.config, Global.asax.cs, etc.

Todo o restante do código foi feito por mim, seja no back ou no front-end.

Abs

**Comment by zanaca** [comment]
:+1:
