### ISSUE TITLE
Exposição de api key

### ISSUE THREAD

**Issue by lgcavalheiro** [hurbcom/challenge-bravo#197]
Boa tarde pessoal!

Possuo um arquivo de configuração que contêm a api key da api externa usada para consseguir as rates atualizadas para as converções, para não expor essa chave, o arquivo de config no remote não contêm ela, quando eu abrir o PR esse arquivo de config vai chegar para vocês sem a chave.

Devo enviar a chave para vocês por algum outro modo, ou vocês conseguem uma api key só para vocês?
(estou usando a https://openexchangerates.org/)

**Comment by naaando** [comment]
No aguardo quanto a essa dúvida também, já vi em outros projetos enviados 👀 o pessoal colocando por trás de uma CDN.

**Comment by zanaca** [comment]
Descrevendo esse ponto no README.md, de como ligar com o processo é sempre válido
