### ISSUE TITLE
Consumo de uma API de terceiros

### ISSUE THREAD

**Issue by nmaia-zz** [hurbcom/challenge-bravo#7]
Pessoal, bom dia.

É permitido que minha API consuma uma API de terceiros para exibição das conversões?

Ex:

- [open exchange rates](https://docs.openexchangerates.org/)
- [currency layer](https://currencylayer.com/documentation)

**Comment by rodrigosdo** [comment]
Boa tarde nmaia.
Esse é inclusive o aconselhável a ser feito. :)
